/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package selanium;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Library {
    public boolean someLibraryMethod() {
    	
    	try {
			// TODO Auto-generated method stub
System.setProperty("webdriver.chrome.driver", "/Users/sunnygupta/Downloads/chromedriver");
			WebDriver driver = new ChromeDriver();
			driver.manage().deleteAllCookies();
			driver.manage().window().maximize();
			driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
			driver.manage().timeouts().pageLoadTimeout(5, TimeUnit.SECONDS);
			driver.get("https://www.google.com/");
			//driver.findElement(By.className("NKcBbdsdsdd")).click();
			driver.close();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
    	
        return true;
    }
    
    public static void main(String[] args) {
		// TODO Auto-generated method stub

    	Library objLib = new Library();
    	objLib.someLibraryMethod();
    	
    	
    	
    }
    
    
}
